spring:
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/guests/**
          filters:
            - AuthenticationFilter

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/res/**
          filters:
            - AuthenticationFilter

        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
